name: docs
on:
  push:
    branches:
      - dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: trigger yunyoujun.github.io
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/YunYouJun/yunyoujun.github.io/dispatches \
            -H 'Authorization: Bearer ${{ secrets.PERSONAL_ACCESS_TOKEN }}' \
            -d '{"event_type":"on-demand-test"}'

      - run: npm i -g pnpm && pnpm i

      - name: Check out vitepress-theme-you
        uses: actions/checkout@master
        with:
          repository: YunYouJun/vitepress-theme-you
          token: ${{ secrets.GITHUB_TOKEN }}
          path: vitepress-theme-you

      - run: cd vitepress-theme-you && pnpm link --global
      - run: cd .. && pnpm link vitepress-theme-you --global
      - run: pnpm build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vitepress/dist/
          force_orphan: true
